### ISSUE TITLE
secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by mlohoar** [automatisch/automatisch#1743]
Hi,
New clean local docker install against a postgres DB on the host.
When I try to login with user@automatisch.io / sample I get a red popup saying "secretOrPrivateKey must have a value".

I have set ENCRYPTION_KEY, WEBHOOK_SECRET_KEY, APP_SECRET_KEY
Is there an additional envirnment variable that I need?

Thanks

**Comment by barinali** [comment]
Hey @mlohoar,

While I think these values should be enough, could you please post the whole error stack?

**Comment by mlohoar** [comment]
Sorry for the delay...
This was the error from ther docker container:
Error: secretOrPrivateKey must have a value
2024-04-02 15:25:08     at Object.module.exports [as sign] (/usr/local/share/.config/yarn/global/node_modules/jsonwebtoken/sign.js:111:20)
2024-04-02 15:25:08     at createAuthTokenByUserId (/usr/local/share/.config/yarn/global/node_modules/@automatisch/backend/dist/src/helpers/create-auth-token-by-user-id.js:10:42)
2024-04-02 15:25:08     at Object.login (/usr/local/share/.config/yarn/global/node_modules/@automatisch/backend/dist/src/graphql/mutations/login.js:13:66)
2024-04-02 15:25:08     at async middleware (/usr/local/share/.config/yarn/global/node_modules/graphql-shield/cjs/generator.js:30:24)
2024-04-02 15:25:08     at async graphqlMiddleware (/usr/local/share/.config/yarn/global/node_modules/express-graphql/index.js:125:26)

Thanks
Murray

**Comment by barinali** [comment]
@mlohoar, this looks like `APP_SECRET_KEY` environment variable has not reached the application runtime. Could you ensure `APP_SECRET_KEY` is available to the application?

Please, keep it in time; this kind of problem might occur due to typos and hidden/not-so-easily-recognizable spaces/characters in the variable names sometimes.

**Comment by mlohoar** [comment]
Hi Ali,
Thanks so much. I had a space in the APP_SECRET_KEY that messed it up and so I deleted the .env file in the automatisch_storage folder compose up and it's working.
Thanks again
Murray

**Comment by barinali** [comment]
@mlohoar you're welcome! I'm closing this issue as resolved in this case.
