### ISSUE TITLE
Notion connection does not load databases

### ISSUE THREAD

**Issue by FilippTrigub** [automatisch/automatisch#2071]
Tried both online and on localhost. Connection is established and Test Connection is green. 

At Set up a trigger, no database can be chose. Periodically, a random database from my notion is indeed shown, before disappearing again.

On localhost I see this error:
main-1      | 2024-09-11 12:17:56:1756 [error]: POST /api/v1/steps/664b2254-b273-4ec4-a5ca-62b76fe044e5/dynamic-data 500
main-1      | 2024-09-11 12:17:56:1756 [error]: TypeError: Cannot read properties of undefined (reading 'plain_text')
main-1      |     at Object.run (file:///automatisch/packages/backend/src/apps/notion/dynamic-data/list-databases/index.js:25:35)
main-1      |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
main-1      |     at async Step.createDynamicData (file:///automatisch/packages/backend/src/models/step.js:249:26)
main-1      |     at async default (file:///automatisch/packages/backend/src/controllers/api/v1/steps/create-dynamic-data.js:12:23)

**Comment by mai1015** [comment]
I got the same problem now, it was working well

**Comment by mai1015** [comment]
I found the issue, when title is empty, it will break the logic, then return empty list

**Comment by barinali** [comment]
Hey all, #2548 should fix the mentioned issue. It'll be in the next release.
