### ISSUE TITLE
yarn db:create 'client password must be a string' even though password is set

### ISSUE THREAD

**Issue by felifluid** [automatisch/automatisch#2115]
Hey!

I'm getting this error when trying to access the postgresql database through yarn.
```
vagrant@vagrant:~/automatisch/packages/backend$ yarn db:create
yarn run v1.22.22
warning package.json: License should be a valid SPDX license expression
$ node ./bin/database/create.js
/home/vagrant/automatisch/packages/backend/node_modules/pg/lib/sasl.js:24
    throw new Error('SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string')
    ^

Error: SASL: SCRAM-SERVER-FIRST-MESSAGE: client password must be a string
    at Object.continueSession (/home/vagrant/automatisch/packages/backend/node_modules/pg/lib/sasl.js:24:11)
    at Client._handleAuthSASLContinue (/home/vagrant/automatisch/packages/backend/node_modules/pg/lib/client.js:257:10)
    at Connection.emit (node:events:519:28)
    at /home/vagrant/automatisch/packages/backend/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/home/vagrant/automatisch/node_modules/pg-protocol/dist/parser.js:40:17)
    at Socket.<anonymous> (/home/vagrant/automatisch/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)

Node.js v22.9.0
error Command failed with exit code 1.
```

This is the postgres part of my `/packages/backend/.env` file:
```
POSTGRES_DATABASE=automatisch_development
POSTGRES_PORT=5432
POSTGRES_HOST=localhost
POSTGRES_USERNAME=automatisch_development_user
POSTGRES_PASSWORD=automatisch_user_password
POSTGRES_ENABLE_SSL=false
```

**Comment by kuba618** [comment]
Hi,
it looks like you are using newer version of PostgreSQL.
In my case when I use latest I have the same error. When using 14.5 as recommended it is working fine.
Cheers.
