### ISSUE TITLE
Fix RSS Error for EU-Startups

### ISSUE THREAD

**Issue by slavakurilyak** [automatisch/automatisch#835]
automatisch v0.3.0 throws the following error when adding EU-Startups RSS:

`Uncaught (in promise)`

Here's the RSS feed for startup podcast:

https://www.eu-startups.com/category/startup-podcast/feed/

<img width="868" alt="error" src="https://user-images.githubusercontent.com/6625584/211441674-6ef10853-7453-49e2-b598-6311aa2d28c9.png">

Here's the error log from Chrome:

```
/flows:1 Denying load of chrome-extension://gacgndbocaddlemdiaadajmlggabdeod/injectedScript.bundle.js. Resources must be listed in the web_accessible_resources manifest key in order to be loaded by pages outside the extension.
chrome-extension://invalid/:1          Failed to load resource: net::ERR_FAILED
index.ts:71 Uncaught (in promise) Error: {"error":"<!DOCTYPE html>\n<html lang=\"en-US\">\n<head>\n    <title>Just a moment...</title>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\n    <meta name=\"robots\" content=\"noindex,nofollow\">\n    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n    <link href=\"/cdn-cgi/styles/challenges.css\" rel=\"stylesheet\">\n    <meta http-equiv=\"refresh\" content=\"35\">\n\n</head>\n<body class=\"no-js\">\n    <div class=\"main-wrapper\" role=\"main\">\n    <div class=\"main-content\">\n        <h1 class=\"zone-name-title h1\">\n            <img class=\"heading-favicon\" src=\"/favicon.ico\"\n                 onerror=\"this.onerror=null;this.parentNode.removeChild(this)\">\n            www.eu-startups.com\n        </h1>\n        <h2 class=\"h2\" id=\"challenge-running\">\n            Checking if the site connection is secure\n        </h2>\n        <noscript>\n            <div id=\"challenge-error-title\">\n                <div class=\"h2\">\n                    <span class=\"icon-wrapper\">\n                        <div class=\"heading-icon warning-icon\"></div>\n                    </span>\n                    <span id=\"challenge-error-text\">\n                        Enable JavaScript and cookies to continue\n                    </span>\n                </div>\n            </div>\n        </noscript>\n        <div id=\"trk_jschal_js\" style=\"display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=7871a5ddfa78eb43')\"></div>\n        <div id=\"challenge-body-text\" class=\"core-msg spacer\">\n            www.eu-startups.com needs to review the security of your connection before proceeding.\n        </div>\n        <form id=\"challenge-form\" action=\"/category/fundin/feed/?__cf_chl_f_tk=zejvWaP6F9bwHZ3vvGO0bYwCZHqBh1z9FVjDQ2yYBkQ-1673314232-0-gaNycGzNBz0\" method=\"POST\" enctype=\"application/x-www-form-urlencoded\">\n            <input type=\"hidden\" name=\"md\" value=\"jA2IB6BCnOHaneBmmv8Lb9njMuFlpTKHYpknIxOqRCg-1673314232-0-Aeb3pZ-uKnmUhhgyTZBdQfYjbXn2TM7kL-EXfKOdCVB0hZPw49FyWwJz3ZOo3VFto2xAQjJrnxlL_DUEThXG3AagFK30foDfnYhxiEpormxk9kGEuM38ud_fZN5vPVmRVU_xdkqbVDmU5FnPoYQJONHDN79jIxzeo_Y-KHRPPbIeMLX13PTaba0w9OY3Zp2Dknzz2z4bflnLb0hzT7DIYw3wSWxk5RR3_cH-3gMzZB74-SH-2fY1NRzUTCGuCFlGwR-l_wxpWwduPIZdyXQoFyXFdFCsbhErrgg-N-gc6b5Ow4Xm9YpiseLjmr8EYjb6L3BVLuZs2pYGWfm-q2RhFA_My7HUkwH8qNSygL599dbXcIZ_SxjWGyqipiE7SHxPmHFIuyW4QuTNw93RyaJqgGYLYKwJ67Z7qDkKuHn2PV-IVqXU4pzHtNaoFsOfZSRq2WciuWnK51KMuSd9nE4hPVv1AIAQFd6D0aaYULj4ycxTmEObuC_3JJDqX-JNfGKkqw\">\n            <input type=\"hidden\" name=\"r\" value=\"l3URaaqZwICBdAnq8ZRQD5Z95vz534j_pFLHCD9gkJo-1673314232-0-AcHyrPLRbINz9touGCoPXEP+BXu/BE25YHCW1VZWP3EwH3cl6obDMVj6NbGrSMSc/Kh+PXMbbm9wVs4gvoHaNWEMvTnM/pUBDAhfm58WH4NnN4KUKBc2qpF/Y26Klqeuo8aTIhPLfMvwCl7AYNyFAQ5zrIwcTQYDSwckQhWODHg6p5I1DF+DD6+Z6WBck3b0TXEXwwpW0ME5eAylkNyRCU3wNNDcxNoaCd0JtrdU/JDHVnHmpaTRO3ndiSOZBluaVGFK70xKzeNcMiw4TxdCZpNfBEcG3F63/Hm62Tx8o06HtRLrgxd5lfsxRbQC56sjfdwUnP5kaYCyHYC+tet22P2VUzCqq+wt93kS1g32st5lWZ2IrInCIz52UAn8kDYjhL6W+n0l9Bd4xNN5qaHdo+vd9nYu05e3j+E8LU86o5aGd7GwaT9OyhqLJQoSURf+kmXvYG3hzngbApAfVc7MoV9Pawt971MhrYbdbmNhUb1bfRh+IpTmLBJywbXb0yd7jdl/8YIxTqTzgIEiW/bF/c2jZLt90KyWRdx9SPv7TiTJ1hnAVdZoP4A3FnOic0eJNROU8IBqAzF940Z8PyUpdYR+j4q4Si8JsDnrn+M2ic98qQvCUmNW93qRx/FPpctWER6lkzXYjIZyyzCUek0jLA9RNLLEYG8+AtFfJDLqnaruEEGhGHDrU/6iH8lqAP/JT+Uw4LCzug0R5pEPDfhpGD8VpfzyiRDT2W3jpavaCD2yD94B/v0eugYD2Q4iXf0OHJm2h9gvfRt1PzvlwhqRCUYIenMhR5au3YiEb2ySELjhclhr2JFmnzEq2uAS22UL3ZK3yI9WCIjnBKwMMsHZd2euc5KLS8AsJ3NRkwm6ILT5PzD8TwvAXRrdWKMPTQfokFBJNsjMnUpamJc4k9bmAwyxGi2XpR3wv/1Ghzmi9fpYKb+PA8tL73TxKwZ2iuu8KwGL1Qfj1Z1IZs5J5p2+0/mbIudGFcgKSGXrA1tOr0y95zbeykIfT+w3EdFhqQaUXXpHXoouFyunDBmTMUNETj+MGWvcwEmA/lgMYnZwNzkAA9oQBK9L0mxct8OgTWClRAQjv8N1XKVHqBwybplb9XTs2p94b6jD0QnABSJRTp0UhUfZNCL/W7SPBH9Y+v6VkjA3o+4vhg74Rv7jRcBcJebtgIgGLne6tFNU0R56XfdmXfKg9tAsM6yQOgAtdtH/QbWcsuLXMYcdtvRw787HnLeuzr4CI/+yg1/PHGA6Gm9YEATu+T+7RtFX212wfIVueEHmh5etd5M39yqL5hHYZfcFlDZQzHClAEOhyLUbCQpAtayTLDLM3EOOaRjdUq00semhcbsXJ/kn2ILqBS9O0xER9+0Z025usZnapvGI5cfpksSK1Gw/36plOQIZBAyxakgbG1Y10jm6ZpG3Rt3wB4GpzhUKCrne9V3RrwueW75f0lZRblYeDn9ns6GroYPanU+W02IJeFFgIjMwtL0Edu9ga71vzmPtPUtoscD7xgDkOMpV6gmHYo+nzKaPyNmYPtMOgbOibS5mJaTgeACqWDUOVuIjYx4zIYcgz39HIltPyBAMgcZ0Ee9GhtOtnCkaJzDFPYsSgg98b0pAiujfXCzozoQlnFcE5u51saCry80M3bGYGDN/vJ2eWzMxQxi0ZpBlyquqLCi6gKEv9kUZmL2xtR/a/J46rPAsQWt8YdH1XdSC73AdnpjDNOfJfH54CDK/KMEYRusQVhXKG6MeH4ZVYieNB25h0Y+aemyPzz/hMY0fgtGCIW1PQrkdeWPT/g==\">\n        </form>\n    </div>\n</div>\n<script>\n    (function(){\n        window._cf_chl_opt={\n            cvId: '2',\n            cType: 'non-interactive',\n            cNounce: '48197',\n            cRay: '7871a5ddfa78eb43',\n            cHash: '0882450d2a1fef8',\n            cUPMDTk: \"\\/category\\/fundin\\/feed\\/?__cf_chl_tk=zejvWaP6F9bwHZ3vvGO0bYwCZHqBh1z9FVjDQ2yYBkQ-1673314232-0-gaNycGzNBz0\",\n            cFPWv: 'b',\n            cTTimeMs: '1000',\n            cTplV: 4,\n            cTplB: 'cf',\n            cRq: {\n                ru: 'aHR0cHM6Ly93d3cuZXUtc3RhcnR1cHMuY29tL2NhdGVnb3J5L2Z1bmRpbi9mZWVkLw==',\n                ra: 'YXhpb3MvMC4yNC4w',\n                rm: 'R0VU',\n                d: 'fQzsoP98HO9WchsxnWXgNXlRKz6XB3RMcH1DSnivKTxgHmtFOLpEQGLVEEOfw9zpGD9/hOuFiCLwzUiB6inhWwkIQDnTbagrVEeeTs2lVly5etF8iuBu9/S06rIhW/1kVm4G3Q8RQA8hbi1wgaWWXioFtbroFdkHAXgyanEj3lryeR9QHaM0x9Z8ZUujqfcil4BuO9u8Wi5BI/AKBR5sJs0VXZt0Oh8qn7b8AyWzVUMInOb6/3A81AeJ8cWmD7XxXr5aqXqr28MjrW0FizqJRfhE3mHUoProwgVBrLsvw85gpHoqvku6H/R32maqNg5t79oB4iIBEdUAKaXNnOxPPhmgfLEpxRX5PsZLGHsGgUhZPOYTI4XKxprHLGUGfnvxE0w3uO6QjJH+/U2nTR7c3VaBwUZBUUXATNpiuZCubqjwOVM30S6QLzdeJUYRDvjP0NjyQ0I8x/Kw7ie2Z3aaljX7lf+6WShelbzQd3+AaYPDcJHRnt1lgMiE2xguOCSTqm7dO2A3HrnqMy+JYAPd2vFHVoAvic8nNZLfn7j+uQ3b4vJRlMRl40PHL32iwO7FWc572pYMaHKNwV3IAifVXIaHVTefMrkI6JsLqHSeqcBNIAINBLR25C2EyHkdZUqgsazrIjwnJ7GzczlM6UY6pA==',\n                t: 'MTY3MzMxNDIzMS45OTQwMDA=',\n                m: 'PLdwVQX8bRvdjrZqiG1lFaefdc2WuvfxaXg7WolfaNg=',\n                i1: 'K5HClErkJQn6iupKQcQzVQ==',\n                i2: 'ZTU9GTiwjoIXNBhwg9yAig==',\n                zh: 'pVVIQWl/3vBz2ML40UYLhal8CLkFnxi1wtWZbD8M0WA=',\n                uh: '/EW1ls7aQMqro/w6J5MT3MpFIPBkG9JaWBXSly5XrwQ=',\n                hh: 'fHMtch/bptL59x/VSUIPmNszW0uME3rHBvmHofx/Uig=',\n            }\n        };\n        var trkjs = document.createElement('img');\n        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=7871a5ddfa78eb43');\n        trkjs.setAttribute('style', 'display: none');\n        document.body.appendChild(trkjs);\n        var cpo = document.createElement('script');\n        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=7871a5ddfa78eb43';\n        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;\n        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;\n        if (window.history && window.history.replaceState) {\n            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;\n            history.replaceState(null, null, \"\\/category\\/fundin\\/feed\\/?__cf_chl_rt_tk=zejvWaP6F9bwHZ3vvGO0bYwCZHqBh1z9FVjDQ2yYBkQ-1673314232-0-gaNycGzNBz0\" + window._cf_chl_opt.cOgUHash);\n            cpo.onload = function() {\n                history.replaceState(null, null, ogU);\n            };\n        }\n        document.getElementsByTagName('head')[0].appendChild(cpo);\n    }());\n</script>\n\n\n    <div class=\"footer\" role=\"contentinfo\">\n        <div class=\"footer-inner\">\n            <div class=\"clearfix diagnostic-wrapper\">\n                <div class=\"ray-id\">Ray ID: <code>7871a5ddfa78eb43</code></div>\n            </div>\n            <div class=\"text-center\">Performance &amp; security by <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com?utm_source=challenge&utm_campaign=j\" target=\"_blank\">Cloudflare</a></div>\n        </div>\n    </div>\n</body>\n</html>\n"}
    at new t (index.ts:71:5)
    at QueryManager.ts:246:15
    at n (asyncMap.ts:30:30)
    at asyncMap.ts:19:47
    at new Promise (<anonymous>)
    at Object.then (asyncMap.ts:19:16)
    at Object.next (asyncMap.ts:31:39)
    at Xo (module.js:132:18)
    at Jo (module.js:176:3)
    at t.next (module.js:225:5)
index.ts:71 Uncaught (in promise) Error: {"error":"<!DOCTYPE html>\n<html lang=\"en-US\">\n<head>\n    <title>Just a moment...</title>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\n    <meta name=\"robots\" content=\"noindex,nofollow\">\n    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n    <link href=\"/cdn-cgi/styles/challenges.css\" rel=\"stylesheet\">\n    <meta http-equiv=\"refresh\" content=\"35\">\n\n</head>\n<body class=\"no-js\">\n    <div class=\"main-wrapper\" role=\"main\">\n    <div class=\"main-content\">\n        <h1 class=\"zone-name-title h1\">\n            <img class=\"heading-favicon\" src=\"/favicon.ico\"\n                 onerror=\"this.onerror=null;this.parentNode.removeChild(this)\">\n            www.eu-startups.com\n        </h1>\n        <h2 class=\"h2\" id=\"challenge-running\">\n            Checking if the site connection is secure\n        </h2>\n        <noscript>\n            <div id=\"challenge-error-title\">\n                <div class=\"h2\">\n                    <span class=\"icon-wrapper\">\n                        <div class=\"heading-icon warning-icon\"></div>\n                    </span>\n                    <span id=\"challenge-error-text\">\n                        Enable JavaScript and cookies to continue\n                    </span>\n                </div>\n            </div>\n        </noscript>\n        <div id=\"trk_jschal_js\" style=\"display:none;background-image:url('/cdn-cgi/images/trace/jsch/nojs/transparent.gif?ray=7871a7f98d56c396')\"></div>\n        <div id=\"challenge-body-text\" class=\"core-msg spacer\">\n            www.eu-startups.com needs to review the security of your connection before proceeding.\n        </div>\n        <form id=\"challenge-form\" action=\"/category/startup-podcast/feed/?__cf_chl_f_tk=8sXJ4U0G4OlCON28gl9qhbqz6ZpHUEzl08Zala_5icY-1673314318-0-gaNycGzNCNE\" method=\"POST\" enctype=\"application/x-www-form-urlencoded\">\n            <input type=\"hidden\" name=\"md\" value=\"ipzHewB5CqjsXR94mc9upFe0uJXQ24H_yYH_p3vuKYQ-1673314318-0-AeCKmFSFrJsk9KASzmIn9fmyA4R2ZeR0MabFokjp_tOc4h7uIk6SGGTO1lBjprVV7wPdI7wv063HaNCMUkqI23AMBYpPmNVJS07kfagJxVeX6n583_yLMmi1o5tDm9mmBhHkzddhshZuhdr0-ZV6CEIRzvHj2d0cx4RPAeoETsJ-wuH5l5G8VoNP7U2qDKOLV-822DCPYSIWxCTNiO5-wbQxIDnKjZMcE3vLVwoW8AxOzVxkhyfgg9Q5SAXUUP394ovco4XXIEGuImHefoawm7Wmd5QmTAmokYk5deteNE3aYz8_maK8mcdJOqP_y6Nh6UMEOt7vGpf6pYF0xSOEmJiekDUxJpzgg46vtyyGP8RfNphu4fIXaIIaxYjhIELNzqpd1j2s8orpQKp2-Bcd5iDwOGVrJ2YXmfmSu_C8kUqqsyEK1hAVFWMw_ipUUv1NHtce1fnvBepsxlJXVywPvkuKbEJ7BoQr9XH-FGsBwrme7GUXti4R1r1JXhj8HzkNJmQNS0UGcxjIs77E_i6GVsk\">\n            <input type=\"hidden\" name=\"r\" value=\"aZEgALJnON2BtykQkfFRzIatpS.dkVQd1pbFULthHm8-1673314318-0-ASPHOzsv8sFEivpiuB2XQomjWHWd5uyw5ewS9dpDTM/zCh6GvEJp9To2mzbAjPbXWKT2ewkesXqurb4K1Pb0Ai0rmsfbWOp4nDQh1YYcpM0McOzEFpS3jqVWD1kQMuLd+om1S/gdl6yriNcyeXxjZdBlSj2o8Q/h7fWEZZneQ7M5K3HSMEdkut6Yz66etwQC0cNLuhM8x9Va37nCLbCzTeckfMKd9xFkPvDDK1hcDk0Nwl5TBYuiH3IKBBbagVIzVY0aTnCFnby2v+YlRXi9hTkU1m7xivqJjf87jQMB/ZRKfVBmiiIFLmKV8SHK94C+MKjzKXyC82u7OqMx0n/NyDquld04/iTS2f8duCuhtOlSxLWT7M/tkteOmZqx8wWyKC71juvnys5jAhcCKe5oiuyGvkJ6hVmZtT2HJrLwE/WwLy/kKFk6Or4gEHU4a2biGNYvOkWhI1f7xhcps9ntw+/6RuxaBWY6+oMmrKmB1f7PmeG8tquR4Yk+vzXH+5NOvRyrhH7eg7NH4DYLwqeKfxzRpwLFLbSDHTu6OVNzInZ5OFIyWD8nzHP9jKIH2ghyGqnZLMieDlwMUvNFS3fs8OdBUi86wqVAbklp/MLVJgb4RMobZeCenk/kT1//I9SfYWiz+fa3Asq0Q4sole2TqAaVEFPF9PrvvlHnMpa8tJOfrhXRKSk7wIFocDNeBQ6K0A1sVHzvj8zRhsGK+uvdnmNG2ZedqygSBIiJQ1FKJnTCLEI212JPg5Wmi0bLuX+/XPL2QMYnzYpPgLPqWOsyjVhYdzF27skpZIjvWQkDt5FDdBkjF5vmbeD85/cdltaxD25vDc/MdPNq6o/raLUwI6OiF+GcuJze0qduo4XV4+z/EhCIWnS3621yAFLuFPqMuoQxUkcXap1s5C1Z7zAvo70VXPUq/tU4U9Lwv1jlgxiIRbWYtU43uLhU90BIljfrP5bLKQHs1ZsDbdHPW5sfiPVrDmyZHUsvQNB+0H8YcuQgJMToUBK4faFIOtIgICP8/e+tXso+hE5QCIC7j/hyBuShJwE5BfnV68ZFiTi9cwO/xjMQstWR1fIxEU0sbV5Vk4T0G13/VQAWiwEKleXM29hIR5QHgvBn/k0vy6wvVlVKOUWQl/hFm54QxyI9c8lLrh86o+3YIUO6pG21BtwQ7xOdRmgnipI1gmVge1xDxBgjMxekRjeCCfmG9OzO19xiVzIITP9aYtpl2jfUrGbDB7tvFCoZCnUmkziI8Co21ecdth0ffj2e4kp0lvy6pfAr0pstyrZhmKs7kDyXMqxfTPCt3TAu7Axhj35qX/AObLmEXHJT/VSEXGxse93IHHvqOXJploppVbunItrjZP6ilShK/5NTWJx0WfqQXUOQCWnvuPChOqtcp7fdIOb52syz8pLgKSyTMBZUj0diRY002+di4jar/Y2/7+rqJ3y/vMDJLDrZ3eD3J2opxgllPjBJwS6nBxkRpPTGBM/a8/1rr/KiTC5P3K3GH3K5NJAC2kyBXjkHYGQAHOH8QO1VJ+agdbjnxYhlvYWcxo3wh9YSjNGv+ZWm277VD7+BGmnf8nxApOv+pZP8Xorvb9kHTjIKQKOfvv6bx2ilnAK4yWPlAcf9KLj0O0/hmWWmwEHF9BYjkQRwXhDIw/vZMmgONtSjFwFl/rlC0NLO1qBb8m/s9adzJZVgHXLCJz/ZabxmLH80eL8JNWOe1WjnmyG1ukl+KrpBTrb/X7ehH1RBuA5NdMGV4BUHahY4DamyX6rvu5ctv78Oe7IP8dmDHWFFEAMNHJFmemzOj2WmszOLb8wj0e3Idj/wJ/J3zmSCHocW7Re3qMv9j1WFdoRbLqxzv7dAgsPPm3g70N1kmGpzPljISHUcNN7/nxN8ZibNPLo7sD4FNsj3JRE30/w0EMbrwqps6NijDA49/Zn0Xd762trFNlRbZacdhC5F3UjP/syMGmJo5KHyV17yqlZaAcoaX2dSQQXSWbDLvqAV+dYovQkyVZPaw4XldUACQxLmA/PvWeqDQ5PQu9B7vgMcOXIuDpXbJ/0W6Whmn/455lkDYKZ/JcmSsUYWkH56rurM1T1fyUpewBZaYtxFg3mOn+eFGfkpW1TzSsQf2Lnhcg3yvSmyCmIPkHJzzm3ucWTeeudX4pEbJHt1K6gciL6iKXyhKtCusS2gQnLF/NgUGUfD9JIRn7A=\">\n        </form>\n    </div>\n</div>\n<script>\n    (function(){\n        window._cf_chl_opt={\n            cvId: '2',\n            cType: 'non-interactive',\n            cNounce: '27787',\n            cRay: '7871a7f98d56c396',\n            cHash: '9f632053f69be5c',\n            cUPMDTk: \"\\/category\\/startup-podcast\\/feed\\/?__cf_chl_tk=8sXJ4U0G4OlCON28gl9qhbqz6ZpHUEzl08Zala_5icY-1673314318-0-gaNycGzNCNE\",\n            cFPWv: 'b',\n            cTTimeMs: '1000',\n            cTplV: 4,\n            cTplB: 'cf',\n            cRq: {\n                ru: 'aHR0cHM6Ly93d3cuZXUtc3RhcnR1cHMuY29tL2NhdGVnb3J5L3N0YXJ0dXAtcG9kY2FzdC9mZWVkLw==',\n                ra: 'YXhpb3MvMC4yNC4w',\n                rm: 'R0VU',\n                d: '7VHOrMGkTizTRuStPaIKbVk2zAwPAn5y6+SAlUzdBRlj0Le9XBpvz0NIiN5WxijlklxErN03MExx32lnaGNiwBP60F8Wb1tKaDRAddZIKptlXBkY2OxnvrexHEURsZCdKLrSr8/k8nwyH5pGQu4GJrutqeKArr2sL8JNRBxJQWS/jzy8ycTDrWi+UopC2KlDFl7HGAfbBndQluBItHC7HGWrisbKyFp8mHumV3auFEu4gWWRzQkKi22RKtlxTsZL1grs6LED0RiH1z+Vm1KycIOPw2Ds1KSMuIm0djVR5oj7LeNGCCeOHdxv/lJHystuFsNkJn5HTZ9Hz+yh+2dcqxyv25xUctUcjLyiVGisILsrsTTqsASE9TfkKj08FU7JkQyqE2UlH/7SwnvxNrjwTttzTMRyLuJomxQa7w4RcQ+aIPB2VmAcwEDufr1Uba6nhp59BpmJz0OV59BP8DNYo7eNab6ANe3pafTPzPdBmsUFl8FdeCoyQobMo+iiOd0ugbgRSOILbU053kKGdvizaLfnH8u1T38E0Rhumz2eLV2jApp5XT22cCTgtF/9DUstFQImFOJDYrrwLU3sSCXI/tvUhOCpHmODusMUvu+AM8hzhyYw8DirL+viQvDE8x+OACcI1+AZ6c2vRWI36ld6GQ==',\n                t: 'MTY3MzMxNDMxOC4zMjgwMDA=',\n                m: 'XYF0Tx48Ol0yRaw5oY6iMS1GzYPc9tmuWFhGH5ucubo=',\n                i1: 'sCkkk5ZmPFJAtSKgFwPAPg==',\n                i2: 'lPQaNNgWaH35DlDn+PYNlA==',\n                zh: 'pVVIQWl/3vBz2ML40UYLhal8CLkFnxi1wtWZbD8M0WA=',\n                uh: '/EW1ls7aQMqro/w6J5MT3MpFIPBkG9JaWBXSly5XrwQ=',\n                hh: 'fHMtch/bptL59x/VSUIPmNszW0uME3rHBvmHofx/Uig=',\n            }\n        };\n        var trkjs = document.createElement('img');\n        trkjs.setAttribute('src', '/cdn-cgi/images/trace/jsch/js/transparent.gif?ray=7871a7f98d56c396');\n        trkjs.setAttribute('style', 'display: none');\n        document.body.appendChild(trkjs);\n        var cpo = document.createElement('script');\n        cpo.src = '/cdn-cgi/challenge-platform/h/b/orchestrate/jsch/v1?ray=7871a7f98d56c396';\n        window._cf_chl_opt.cOgUHash = location.hash === '' && location.href.indexOf('#') !== -1 ? '#' : location.hash;\n        window._cf_chl_opt.cOgUQuery = location.search === '' && location.href.slice(0, -window._cf_chl_opt.cOgUHash.length).indexOf('?') !== -1 ? '?' : location.search;\n        if (window.history && window.history.replaceState) {\n            var ogU = location.pathname + window._cf_chl_opt.cOgUQuery + window._cf_chl_opt.cOgUHash;\n            history.replaceState(null, null, \"\\/category\\/startup-podcast\\/feed\\/?__cf_chl_rt_tk=8sXJ4U0G4OlCON28gl9qhbqz6ZpHUEzl08Zala_5icY-1673314318-0-gaNycGzNCNE\" + window._cf_chl_opt.cOgUHash);\n            cpo.onload = function() {\n                history.replaceState(null, null, ogU);\n            };\n        }\n        document.getElementsByTagName('head')[0].appendChild(cpo);\n    }());\n</script>\n\n\n    <div class=\"footer\" role=\"contentinfo\">\n        <div class=\"footer-inner\">\n            <div class=\"clearfix diagnostic-wrapper\">\n                <div class=\"ray-id\">Ray ID: <code>7871a7f98d56c396</code></div>\n            </div>\n            <div class=\"text-center\">Performance &amp; security by <a rel=\"noopener noreferrer\" href=\"https://www.cloudflare.com?utm_source=challenge&utm_campaign=j\" target=\"_blank\">Cloudflare</a></div>\n        </div>\n    </div>\n</body>\n</html>\n"}
    at new t (index.ts:71:5)
    at QueryManager.ts:246:15
    at n (asyncMap.ts:30:30)
    at asyncMap.ts:19:47
    at new Promise (<anonymous>)
    at Object.then (asyncMap.ts:19:16)
    at Object.next (asyncMap.ts:31:39)
    at Xo (module.js:132:18)
    at Jo (module.js:176:3)
    at t.next (module.js:225:5)

```

**Comment by LostOnTheLine** [comment]
> @slavakurilyak, thanks for creating the issue and sharing the corresponding error. I have just tested the same RSS feed, and it worked. Thanks to the error message you shared, I see that your trigger test was stuck at the Cloudflare security check. 
> I mimicked that page using the HTML code you shared in the error payload. While this is not necessarily a bug in the RSS parser, we need to see how we can improve Automatisch against the automated security checks. To investigate further, I'll leave this issue open, but there may not be a quick iteration.

I just ran into a similar situation, an RSS Feed that the URL goes to a Cloudflare security check & can't be used properly. So this issue would be nice to see fixed as it may help mine as well

**Comment by barinali** [comment]
> > @slavakurilyak, thanks for creating the issue and sharing the corresponding error. I have just tested the same RSS feed, and it worked. Thanks to the error message you shared, I see that your trigger test was stuck at the Cloudflare security check.
> > I mimicked that page using the HTML code you shared in the error payload. While this is not necessarily a bug in the RSS parser, we need to see how we can improve Automatisch against the automated security checks. To investigate further, I'll leave this issue open, but there may not be a quick iteration.
> 
> I just ran into a similar situation, an RSS Feed that the URL goes to a Cloudflare security check & can't be used properly. So this issue would be nice to see fixed as it may help mine as well

I've been looking at this matter on and off for a while now since the issue's creation. However, I need help to come up with any improvement we can provide from the Automatisch perspective.

You can find the relevant page from CF [here](https://developers.cloudflare.com/support/firewall/settings/understanding-the-cloudflare-security-level/). They'll refer to [Project Honeypot](https://www.projecthoneypot.org/) along with their internal logic. One may contact Project Honeypot to clear any mislabelled data. Apart from these, it still needs to be determined how we can improve from the Automatisch perspective. I'm open to hearing your suggestions. @LostOnTheLine

**Comment by LostOnTheLine** [comment]
> You can find the relevant page from CF [here](https://developers.cloudflare.com/support/firewall/settings/understanding-the-cloudflare-security-level/). They'll refer to [Project Honeypot](https://www.projecthoneypot.org/) along with their internal logic. One may contact Project Honeypot to clear any mislabelled data. Apart from these, it still needs to be determined how we can improve from the Automatisch perspective. I'm open to hearing your suggestions. @LostOnTheLine

I'm not really sure what to suggest. I think the biggest problem is that the RSS Feeds are created by default because they use a Website Builder like WordPress so they don't even know it's there & are more concerned with things like preventing DDoS. I was hoping there'd be a solution, but not expecting one

**Comment by Beastofhell27** [comment]
Hello, I've had a similar issue where cloudflare blocks automatisch. I recently came across FlareSolverr https://github.com/FlareSolverr/FlareSolverr

i have no idea if this can work nor if this can be implemented into automatisch. I'm not a dev nor expert but it seems that it could work.
